using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.EP.WebGpu;
using Microsoft.ML.OnnxRuntime.Tensors;
using Microsoft.ML.OnnxRuntimeGenAI;
using System.Linq;

Console.WriteLine("=== WebGPU EP Plugin Test ===");
Console.WriteLine($"OS: {System.Runtime.InteropServices.RuntimeInformation.OSDescription}");
Console.WriteLine($"Arch: {System.Runtime.InteropServices.RuntimeInformation.OSArchitecture}\n");

// ---- Step 1: Plugin library ----
var env = OrtEnv.Instance();
string libPath = WebGpuEp.GetLibraryPath();
Console.WriteLine($"Library path: {libPath}");
Console.WriteLine($"EP name:     {WebGpuEp.GetEpName()}");
Console.WriteLine($"EP names:    [{string.Join(", ", WebGpuEp.GetEpNames())}]");
Console.WriteLine($"File exists: {File.Exists(libPath)}\n");

// Companion DLLs
string libDir = Path.GetDirectoryName(libPath)!;
Console.WriteLine("Companion DLLs:");
foreach (var f in new[] { "dxil.dll", "dxcompiler.dll", "onnxruntime.dll", "onnxruntime_providers_webgpu.dll" })
{
    string path = Path.Combine(libDir, f);
    Console.WriteLine($"  {f,-45} {(File.Exists(path) ? $"✓ ({new FileInfo(path).Length / 1024} KB)" : "✗ MISSING")}");
}
Console.WriteLine();

// ---- Step 2: Registration ----
var registered = false;
Console.WriteLine("--- Registration ---");
try
{
    env.RegisterExecutionProviderLibrary("webgpu_ep", libPath);
    registered = true;
    Console.WriteLine("  ✓ Registered successfully\n");
}
catch (Exception ex)
{
    Console.WriteLine($"  ✗ FAILED: {ex.GetType().Name}: {ex.Message}");
    if (ex.InnerException is not null) Console.WriteLine($"    Inner: {ex.InnerException.Message}");
    Console.WriteLine("\n=== FAILED AT REGISTRATION ===");
    return;
}

try
{
    // ---- Step 3: Enumerate devices ----
    Console.WriteLine("--- Device Enumeration ---");
    OrtEpDevice? webGpuDevice = null;
    try
    {
        var devices = env.GetEpDevices();
        Console.WriteLine($"  Total devices: {devices.Count}");
        foreach (var d in devices)
        {
            Console.WriteLine($"  [{d.EpName}] Vendor={d.EpVendor} HwType={d.HardwareDevice.Type} VendorId=0x{d.HardwareDevice.VendorId:X}");
            if (string.Equals(d.EpName, WebGpuEp.GetEpName(), StringComparison.OrdinalIgnoreCase))
                webGpuDevice = d;
        }

        if (webGpuDevice is null)
        {
            Console.WriteLine("  ✗ No WebGPU EP device found\n");
            Console.WriteLine("=== FAILED AT DEVICE ENUMERATION ===");
            return;
        }
        Console.WriteLine($"  ✓ Found: {webGpuDevice.EpName} (Vendor={webGpuDevice.EpVendor}, HW={webGpuDevice.HardwareDevice.Type})\n");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"  ✗ FAILED: {ex.Message}\n");
        Console.WriteLine("=== FAILED AT DEVICE ENUMERATION ===");
        return;
    }

    // ---- Step 4: Inference ----
    Console.WriteLine("--- Simple Inference (Add) ---");
    try
    {
        // Use pre-generated add_test.onnx (generated by converter .venv python)
        string modelFile = Path.Combine(AppContext.BaseDirectory, "add_test.onnx");
        Console.WriteLine($"  Model: {Path.GetFileName(modelFile)}");
        Console.WriteLine($"  Exists: {File.Exists(modelFile)}");

        using var sessionOptions = new SessionOptions();
        sessionOptions.AppendExecutionProvider(env, [webGpuDevice], new Dictionary<string, string>());

        using var session = new InferenceSession(modelFile, sessionOptions);
        Console.WriteLine("  ✓ Session created");

        // Run: 3.0 + 5.0 = 8.0
        var inputA = new DenseTensor<float>([1]);
        inputA[0] = 3.0f;
        var inputB = new DenseTensor<float>([1]);
        inputB[0] = 5.0f;

        var inputs = new List<NamedOnnxValue>
        {
            NamedOnnxValue.CreateFromTensor("A", inputA),
            NamedOnnxValue.CreateFromTensor("B", inputB)
        };

        using var results = session.Run(inputs);
        var output = results.First().AsTensor<float>();

        Console.WriteLine($"  3.0 + 5.0 = {output[0]:F1} (expected 8.0)");
        Console.WriteLine(output[0] == 8.0f ? "  ✓ Correct!\n" : "  ✗ WRONG!\n");

        Console.WriteLine("=== SIMPLE TEST SUCCESS ===");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"  ✗ FAILED: {ex.GetType().Name}: {ex.Message}");
        if (ex.InnerException is not null) Console.WriteLine($"    Inner: {ex.InnerException.Message}");
        Console.WriteLine("=== SIMPLE TEST FAILED ===");
    }

    // ---- Step 5: Real encoder.onnx test ----
    string encoderPath = @"E:\Work\Dimq1\Audio\Models\nemotron-3.5-asr-streaming-0.6b-onnx-fp32-cpu\encoder.onnx";
    if (File.Exists(encoderPath))
    {
        Console.WriteLine($"--- Real Encoder Test ---");
        Console.WriteLine($"  Model: {encoderPath}");
        Console.WriteLine($"  Size: {new FileInfo(encoderPath).Length / 1024.0 / 1024.0:F1} MB");

        try
        {
            using var encoderOpts = new SessionOptions();
            encoderOpts.AppendExecutionProvider(env, [webGpuDevice], new Dictionary<string, string>());

            var sw = System.Diagnostics.Stopwatch.StartNew();
            using var encoderSession = new InferenceSession(encoderPath, encoderOpts);
            sw.Stop();
            Console.WriteLine($"  ✓ Session created in {sw.Elapsed.TotalSeconds:F1}s");

            // Try to get EP assignment info
            sw.Restart();
            Console.WriteLine($"  Inputs: {encoderSession.InputMetadata.Count}, Outputs: {encoderSession.OutputMetadata.Count}");
            foreach (var inp in encoderSession.InputMetadata)
                Console.WriteLine($"    in: {inp.Key} [{string.Join(",", inp.Value.Dimensions)}] {inp.Value.ElementType}");
            foreach (var out_ in encoderSession.OutputMetadata)
                Console.WriteLine($"    out: {out_.Key} [{string.Join(",", out_.Value.Dimensions)}] {out_.Value.ElementType}");

            Console.WriteLine($"  Metadata collected in {sw.Elapsed.TotalSeconds:F1}s");

            // Quick forward pass with random data to verify execution
            sw.Restart();
            var rng = new Random(42);
            var audio = new float[1 * 65 * 128];
            for (int j = 0; j < audio.Length; j++) audio[j] = (float)(rng.NextDouble() * 2 - 1);
            var audioTensor = new DenseTensor<float>(audio, [1, 65, 128]);

            var inputs = new List<NamedOnnxValue>
            {
                NamedOnnxValue.CreateFromTensor("audio_signal", audioTensor),
                NamedOnnxValue.CreateFromTensor("length", new DenseTensor<long>(new long[]{65}, [1])),
                NamedOnnxValue.CreateFromTensor("cache_last_channel", new DenseTensor<float>(new float[1*24*70*1024], [1,24,70,1024])),
                NamedOnnxValue.CreateFromTensor("cache_last_time", new DenseTensor<float>(new float[1*24*1024*8], [1,24,1024,8])),
                NamedOnnxValue.CreateFromTensor("cache_last_channel_len", new DenseTensor<long>(new long[]{0}, [1])),
                NamedOnnxValue.CreateFromTensor("lang_id", new DenseTensor<long>(new long[]{25}, [1]))
            };

            using var encoderResults = encoderSession.Run(inputs);
            sw.Stop();

            Console.WriteLine($"  ✓ Forward pass: {sw.Elapsed.TotalMilliseconds:F0}ms");
            int idx = 0;
            foreach (var r in encoderResults)
            {
                try
                {
                    var t = r.AsTensor<float>();
                    if (t != null)
                    {
                        var arr = t.ToArray();
                        var dims = t.Dimensions.ToArray();
                        Console.WriteLine($"    [{idx}] [{string.Join(",", dims)}] range=[{arr.Min():F3}, {arr.Max():F3}]");
                    }
                    else
                        Console.WriteLine($"    [{idx}] non-float");
                }
                catch { Console.WriteLine($"    [{idx}] (could not read)"); }
                idx++;
            }
            Console.WriteLine("  ✓ Encoder model infers correctly on WebGPU EP");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"  ✗ FAILED: {ex.GetType().Name}: {ex.Message}");
            string msg = ex.InnerException?.Message ?? ex.Message;
            if (msg.Length > 300) msg = msg[..300] + "...";
            Console.WriteLine($"    Detail: {msg}");
        }
    }
    else
    {
        Console.WriteLine($"--- Real Encoder Test ---");
        Console.WriteLine($"  ✗ Model not found at: {encoderPath}");
    }

    // ---- Step 6: GenAI Model with WebGPU ----
    string modelPath = @"E:\Work\Dimq1\Audio\Models\nemotron-3.5-asr-streaming-0.6b-onnx-fp32-cpu";
    if (Directory.Exists(modelPath) && File.Exists(Path.Combine(modelPath, "genai_config.json")))
    {
        Console.WriteLine("--- GenAI Model with WebGPU ---");
        Console.WriteLine($"  Model path: {modelPath}");

        try
        {
            // Try approach 1: GenAI Config with "webgpu" provider name
            var config = new Config(modelPath);
            config.ClearProviders();
            config.AppendProvider("webgpu");
            Console.WriteLine("  Config: providers cleared, 'webgpu' appended");

            Console.Write("  Creating model... ");
            var sw = System.Diagnostics.Stopwatch.StartNew();
            using var model = new Model(config);
            sw.Stop();
            Console.WriteLine($"OK ({sw.Elapsed.TotalSeconds:F1}s)");

            // Try creating streaming processor
            using var processor = new StreamingProcessor(model);
            Console.WriteLine($"  StreamingProcessor: OK");

            using var tokenizer = new Tokenizer(model);
            using var tokenizerStream = tokenizer.CreateStream();
            using var genParams = new GeneratorParams(model);
            using var generator = new Generator(model, genParams);
            Console.WriteLine($"  Generator: OK");

            // Try a dummy audio chunk
            var sampleRate = 16000;
            var chunkSize = 8960; // 560ms @ 16kHz
            var dummyAudio = new float[chunkSize];
            for (int j = 0; j < dummyAudio.Length; j++)
                dummyAudio[j] = (float)(Math.Sin(2 * Math.PI * 440 * j / sampleRate) * 0.5);

            Console.Write($"  Processing {chunkSize} samples... ");
            sw.Restart();
            var inputs = processor.Process(dummyAudio);
            sw.Stop();
            Console.WriteLine($"({sw.Elapsed.TotalMilliseconds:F0}ms) -> {(inputs != null ? "NamedTensors ready" : "buffering")}");

            if (inputs != null)
            {
                Console.Write("  Generator.SetInputs + GenerateNextToken... ");
                sw.Restart();
                generator.SetInputs(inputs);
                while (!generator.IsDone())
                    generator.GenerateNextToken();
                sw.Stop();
                var newTokens = generator.GetNextTokens();
                Console.WriteLine($"({sw.Elapsed.TotalMilliseconds:F0}ms)");
                Console.WriteLine($"    New tokens: {newTokens.Length}");
            }

            // Flush
            Console.Write("  Flush... ");
            sw.Restart();
            using var flushInputs = processor.Flush();
            if (flushInputs != null)
            {
                generator.SetInputs(flushInputs);
                while (!generator.IsDone())
                    generator.GenerateNextToken();
                var newTokens2 = generator.GetNextTokens();
                Console.WriteLine($"({sw.Elapsed.TotalMilliseconds:F0}ms) -> {newTokens2.Length} tokens");
            }
            else
                Console.WriteLine("no pending audio");

            Console.WriteLine("  ✓ GenAI model runs on WebGPU EP");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"  ✗ FAILED: {ex.GetType().Name}: {ex.Message}");
            string msg = ex.InnerException?.Message ?? ex.Message;
            if (msg.Length > 300) msg = msg[..300] + "...";
            Console.WriteLine($"    Detail: {msg}");
        }
    }
    else
    {
        Console.WriteLine("--- GenAI Model with WebGPU ---");
        Console.WriteLine($"  ✗ Model not found at: {modelPath}");
    }
}
finally
{
    env.UnregisterExecutionProviderLibrary("webgpu_ep");
    Console.WriteLine("Unregistered WebGPU EP.");
}

Console.WriteLine("\nDone.");
