using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.EP.WebGpu;
using Microsoft.ML.OnnxRuntime.Tensors;
using Microsoft.ML.OnnxRuntimeGenAI;
using NAudio.Wave;
using NAudio.Wave.SampleProviders;
using System.Linq;
using System.Text.Json;

Console.WriteLine("=== WebGPU EP Plugin Test ===");
Console.WriteLine($"OS: {System.Runtime.InteropServices.RuntimeInformation.OSDescription}");
Console.WriteLine($"Arch: {System.Runtime.InteropServices.RuntimeInformation.OSArchitecture}\n");

// ---- Step 1: Plugin library ----
var env = OrtEnv.Instance();
string libPath = WebGpuEp.GetLibraryPath();
Console.WriteLine($"Library path: {libPath}");
Console.WriteLine($"EP name:     {WebGpuEp.GetEpName()}");
Console.WriteLine($"EP names:    [{string.Join(", ", WebGpuEp.GetEpNames())}]");
Console.WriteLine($"File exists: {File.Exists(libPath)}\n");

// Companion DLLs
string libDir = Path.GetDirectoryName(libPath)!;
Console.WriteLine("Companion DLLs:");
foreach (var f in new[] { "dxil.dll", "dxcompiler.dll", "onnxruntime.dll", "onnxruntime_providers_webgpu.dll" })
{
    string path = Path.Combine(libDir, f);
    Console.WriteLine($"  {f,-45} {(File.Exists(path) ? $"✓ ({new FileInfo(path).Length / 1024} KB)" : "✗ MISSING")}");
}
Console.WriteLine();

// ---- Step 2: Registration ----
var registered = false;
Console.WriteLine("--- Registration ---");
try
{
    env.RegisterExecutionProviderLibrary("webgpu_ep", libPath);
    registered = true;
    Console.WriteLine("  ✓ Registered successfully\n");
}
catch (Exception ex)
{
    Console.WriteLine($"  ✗ FAILED: {ex.GetType().Name}: {ex.Message}");
    if (ex.InnerException is not null) Console.WriteLine($"    Inner: {ex.InnerException.Message}");
    Console.WriteLine("\n=== FAILED AT REGISTRATION ===");
    return;
}

try
{
    // ---- Step 3: Enumerate devices ----
    Console.WriteLine("--- Device Enumeration ---");
    OrtEpDevice? webGpuDevice = null;
    try
    {
        var devices = env.GetEpDevices();
        Console.WriteLine($"  Total devices: {devices.Count}");
        foreach (var d in devices)
        {
            Console.WriteLine($"  [{d.EpName}] Vendor={d.EpVendor} HwType={d.HardwareDevice.Type} VendorId=0x{d.HardwareDevice.VendorId:X}");
            if (string.Equals(d.EpName, WebGpuEp.GetEpName(), StringComparison.OrdinalIgnoreCase))
                webGpuDevice = d;
        }

        if (webGpuDevice is null)
        {
            Console.WriteLine("  ✗ No WebGPU EP device found\n");
            Console.WriteLine("=== FAILED AT DEVICE ENUMERATION ===");
            return;
        }
        Console.WriteLine($"  ✓ Found: {webGpuDevice.EpName} (Vendor={webGpuDevice.EpVendor}, HW={webGpuDevice.HardwareDevice.Type})\n");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"  ✗ FAILED: {ex.Message}\n");
        Console.WriteLine("=== FAILED AT DEVICE ENUMERATION ===");
        return;
    }

    // ---- Step 4: Inference ----
    Console.WriteLine("--- Simple Inference (Add) ---");
    try
    {
        // Use pre-generated add_test.onnx (generated by converter .venv python)
        string modelFile = Path.Combine(AppContext.BaseDirectory, "add_test.onnx");
        Console.WriteLine($"  Model: {Path.GetFileName(modelFile)}");
        Console.WriteLine($"  Exists: {File.Exists(modelFile)}");

        using var sessionOptions = new SessionOptions();
        sessionOptions.AppendExecutionProvider(env, [webGpuDevice], new Dictionary<string, string>());

        using var session = new InferenceSession(modelFile, sessionOptions);
        Console.WriteLine("  ✓ Session created");

        // Run: 3.0 + 5.0 = 8.0
        var inputA = new DenseTensor<float>([1]);
        inputA[0] = 3.0f;
        var inputB = new DenseTensor<float>([1]);
        inputB[0] = 5.0f;

        var inputs = new List<NamedOnnxValue>
        {
            NamedOnnxValue.CreateFromTensor("A", inputA),
            NamedOnnxValue.CreateFromTensor("B", inputB)
        };

        using var results = session.Run(inputs);
        var output = results.First().AsTensor<float>();

        Console.WriteLine($"  3.0 + 5.0 = {output[0]:F1} (expected 8.0)");
        Console.WriteLine(output[0] == 8.0f ? "  ✓ Correct!\n" : "  ✗ WRONG!\n");

        Console.WriteLine("=== SIMPLE TEST SUCCESS ===");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"  ✗ FAILED: {ex.GetType().Name}: {ex.Message}");
        if (ex.InnerException is not null) Console.WriteLine($"    Inner: {ex.InnerException.Message}");
        Console.WriteLine("=== SIMPLE TEST FAILED ===");
    }

    // ---- Step 5: Real encoder.onnx test ----
    string encoderPath = @"E:\Work\Dimq1\Audio\Models\nemotron-3.5-asr-streaming-0.6b-onnx-fp32-cpu\encoder.onnx";
    if (File.Exists(encoderPath))
    {
        Console.WriteLine($"--- Real Encoder Test ---");
        Console.WriteLine($"  Model: {encoderPath}");
        Console.WriteLine($"  Size: {new FileInfo(encoderPath).Length / 1024.0 / 1024.0:F1} MB");

        try
        {
            using var encoderOpts = new SessionOptions();
            encoderOpts.AppendExecutionProvider(env, [webGpuDevice], new Dictionary<string, string>());

            var sw = System.Diagnostics.Stopwatch.StartNew();
            using var encoderSession = new InferenceSession(encoderPath, encoderOpts);
            sw.Stop();
            Console.WriteLine($"  ✓ Session created in {sw.Elapsed.TotalSeconds:F1}s");

            // Try to get EP assignment info
            sw.Restart();
            Console.WriteLine($"  Inputs: {encoderSession.InputMetadata.Count}, Outputs: {encoderSession.OutputMetadata.Count}");
            foreach (var inp in encoderSession.InputMetadata)
                Console.WriteLine($"    in: {inp.Key} [{string.Join(",", inp.Value.Dimensions)}] {inp.Value.ElementType}");
            foreach (var out_ in encoderSession.OutputMetadata)
                Console.WriteLine($"    out: {out_.Key} [{string.Join(",", out_.Value.Dimensions)}] {out_.Value.ElementType}");

            Console.WriteLine($"  Metadata collected in {sw.Elapsed.TotalSeconds:F1}s");

            // Quick forward pass with random data to verify execution
            sw.Restart();
            var rng = new Random(42);
            var audio = new float[1 * 65 * 128];
            for (int j = 0; j < audio.Length; j++) audio[j] = (float)(rng.NextDouble() * 2 - 1);
            var audioTensor = new DenseTensor<float>(audio, [1, 65, 128]);

            var inputs = new List<NamedOnnxValue>
            {
                NamedOnnxValue.CreateFromTensor("audio_signal", audioTensor),
                NamedOnnxValue.CreateFromTensor("length", new DenseTensor<long>(new long[]{65}, [1])),
                NamedOnnxValue.CreateFromTensor("cache_last_channel", new DenseTensor<float>(new float[1*24*70*1024], [1,24,70,1024])),
                NamedOnnxValue.CreateFromTensor("cache_last_time", new DenseTensor<float>(new float[1*24*1024*8], [1,24,1024,8])),
                NamedOnnxValue.CreateFromTensor("cache_last_channel_len", new DenseTensor<long>(new long[]{0}, [1])),
                NamedOnnxValue.CreateFromTensor("lang_id", new DenseTensor<long>(new long[]{25}, [1]))
            };

            using var encoderResults = encoderSession.Run(inputs);
            sw.Stop();

            Console.WriteLine($"  ✓ Forward pass: {sw.Elapsed.TotalMilliseconds:F0}ms");
            int idx = 0;
            foreach (var r in encoderResults)
            {
                try
                {
                    var t = r.AsTensor<float>();
                    if (t != null)
                    {
                        var arr = t.ToArray();
                        var dims = t.Dimensions.ToArray();
                        Console.WriteLine($"    [{idx}] [{string.Join(",", dims)}] range=[{arr.Min():F3}, {arr.Max():F3}]");
                    }
                    else
                        Console.WriteLine($"    [{idx}] non-float");
                }
                catch { Console.WriteLine($"    [{idx}] (could not read)"); }
                idx++;
            }
            Console.WriteLine("  ✓ Encoder model infers correctly on WebGPU EP");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"  ✗ FAILED: {ex.GetType().Name}: {ex.Message}");
            string msg = ex.InnerException?.Message ?? ex.Message;
            if (msg.Length > 300) msg = msg[..300] + "...";
            Console.WriteLine($"    Detail: {msg}");
        }
    }
    else
    {
        Console.WriteLine($"--- Real Encoder Test ---");
        Console.WriteLine($"  ✗ Model not found at: {encoderPath}");
    }

    // ---- Step 6: GenAI Streaming ASR with WebGPU (real audio) ----
    string modelPath = @"E:\Work\Dimq1\Audio\Models\nemotron-3.5-asr-streaming-0.6b-onnx-fp32-cpu";
    string audioPath = @"E:\Work\Dimq1\Audio\nemotron-speech-csharp\Test-Audio\sample-0.mp3";

    if (!Directory.Exists(modelPath))
    {
        Console.WriteLine($"--- GenAI ASR with WebGPU ---");
        Console.WriteLine($"  ✗ Model path not found: {modelPath}");
    }
    else if (!File.Exists(audioPath))
    {
        Console.WriteLine($"--- GenAI ASR with WebGPU ---");
        Console.WriteLine($"  ✗ Audio not found: {audioPath}");
    }
    else
    {
        Console.WriteLine("--- GenAI Streaming ASR (Real Audio) ---");
        Console.WriteLine($"  Model: {modelPath}");
        Console.WriteLine($"  Audio: {audioPath}");

        try
        {
            // Read config
            using var cfgJson = JsonDocument.Parse(File.ReadAllText(Path.Combine(modelPath, "genai_config.json")));
            int sampleRate = cfgJson.RootElement.GetProperty("model").GetProperty("sample_rate").GetInt32();
            int chunkSize = cfgJson.RootElement.GetProperty("model").GetProperty("chunk_samples").GetInt32();
            Console.WriteLine($"  Sample rate: {sampleRate} Hz, Chunk: {chunkSize} samples");

            // Load audio
            using var reader = new NAudio.Wave.AudioFileReader(audioPath);
            var source = (NAudio.Wave.ISampleProvider)reader;
            if (reader.WaveFormat.Channels > 1)
                source = new NAudio.Wave.SampleProviders.StereoToMonoSampleProvider(source);
            if (reader.WaveFormat.SampleRate != sampleRate)
                source = new NAudio.Wave.SampleProviders.WdlResamplingSampleProvider(source, sampleRate);

            var audioList = new List<float>();
            float[] buf = new float[4096];
            int read;
            while ((read = source.Read(buf, 0, buf.Length)) > 0)
                audioList.AddRange(buf.Take(read));
            float[] audio = audioList.ToArray();
            double duration = audio.Length / (double)sampleRate;
            Console.WriteLine($"  Audio: {duration:F1}s ({audio.Length} samples)");

            // GenAI config with WebGPU
            var config = new Config(modelPath);
            config.ClearProviders();
            config.AppendProvider("webgpu");

            Console.Write("  Creating model... ");
            var sw = System.Diagnostics.Stopwatch.StartNew();
            using var model = new Model(config);
            sw.Stop();
            Console.WriteLine($"OK ({sw.Elapsed.TotalSeconds:F1}s)");

            using var processor = new StreamingProcessor(model);
            using var tokenizer = new Tokenizer(model);
            using var tokenizerStream = tokenizer.CreateStream();
            using var genParams = new GeneratorParams(model);
            using var generator = new Generator(model, genParams);

            Console.WriteLine(new string('-', 60));

            // Stream audio in chunks — accumulate mel, run all at once
            sw.Restart();
            int chunks = 0;

            for (int i = 0; i < audio.Length; i += chunkSize)
            {
                int remaining = Math.Min(chunkSize, audio.Length - i);
                var chunk = audio[i..(i + remaining)];
                chunks++;

                using var inputs = processor.Process(chunk);
                if (inputs is null) continue;

                generator.SetInputs(inputs);
                while (!generator.IsDone())
                    generator.GenerateNextToken();
            }

            // Flush remaining
            using var flushInputs = processor.Flush();
            if (flushInputs is not null)
            {
                generator.SetInputs(flushInputs);
                while (!generator.IsDone())
                    generator.GenerateNextToken();
            }

            sw.Stop();

            // Decode ALL tokens at once from the full sequence
            var seq = generator.GetSequence(0);
            string transcript = "";
            foreach (var token in seq)
                transcript += tokenizerStream.Decode(token);
            double rtf = duration / sw.Elapsed.TotalSeconds;

            Console.WriteLine();
            Console.WriteLine(new string('=', 60));
            Console.WriteLine($"  {transcript.Trim()}");
            Console.WriteLine(new string('=', 60));
            Console.WriteLine($"  Audio: {duration:F2}s | Wall: {sw.Elapsed.TotalSeconds:F2}s | RTF: {rtf:F2}x");
            Console.WriteLine($"  Chunks: {chunks}, Tokens: {seq.Length}");
            Console.WriteLine("  ✓ GenAI Nemotron streaming ASR works on WebGPU EP");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"  ✗ FAILED: {ex.GetType().Name}: {ex.Message}");
            if (ex.InnerException is not null)
                Console.WriteLine($"    Inner: {ex.InnerException.Message}");
        }
    }
}
finally
{
    env.UnregisterExecutionProviderLibrary("webgpu_ep");
    Console.WriteLine("Unregistered WebGPU EP.");
}

Console.WriteLine("\nDone.");
